/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsSysproxy {
  host: string
  port: number
  bypass: string
  enable: boolean
}
export interface JsAutoproxy {
  url: string
  enable: boolean
}
export declare function getSystemProxy(): JsSysproxy
export declare function setSystemProxy(proxy: JsSysproxy): void
export declare function getAutoProxy(): JsAutoproxy
export declare function setAutoProxy(proxy: JsAutoproxy): void
