/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SysproxyInfo {
  enable: boolean
  host: string
  port: number
  bypass: string
}
export interface AutoproxyInfo {
  enable: boolean
  url: string
}
export declare function triggerManualProxy(enable: boolean, host: string, port: number, bypass: string): void
export declare function triggerAutoProxy(enable: boolean, url: string): void
export declare function getSystemProxy(): SysproxyInfo
export declare function getAutoProxy(): AutoproxyInfo
