/* auto-generated by NAPI-RS */
 
export declare function getAutoProxy(): JsAutoproxy

export declare function getSystemProxy(): JsSysproxy

export interface JsAutoproxy {
  url: string
  enable: boolean
}

export interface JsSysproxy {
  host: string
  port: number
  bypass: string
  enable: boolean
}

export declare function setAutoProxy(proxy: JsAutoproxy): void

export declare function setSystemProxy(proxy: JsSysproxy): void

export declare function triggerAutoProxy(enable: boolean, url: string): void

export declare function triggerManualProxy(enable: boolean, host: string, port: number, bypass: string): void
